//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Car/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Car"",
            ""id"": ""c231403f-0c6d-40e9-a9fc-d31d312d7ac3"",
            ""actions"": [
                {
                    ""name"": ""Nitro"",
                    ""type"": ""Button"",
                    ""id"": ""78da97da-5aac-4d06-a8d4-cdf29ed784bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateForward"",
                    ""type"": ""Button"",
                    ""id"": ""372ad4bc-1c03-454d-a90e-c534ebd7b200"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateBack"",
                    ""type"": ""Button"",
                    ""id"": ""78eb68be-8f11-4e04-b6e6-5a73ae1fde1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableAutoMove"",
                    ""type"": ""Button"",
                    ""id"": ""2f12ae59-b016-4624-9d8c-34f22396f40d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableAutoMove"",
                    ""type"": ""Button"",
                    ""id"": ""916bde01-77bf-4c28-92f8-af8475bf7cd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba1e3600-4509-466e-9f91-b481c521d3a2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nitro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57213c77-4317-48c4-84cc-51391ab17927"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ec857d9-56b0-46b2-861c-ff1921a01833"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""439797a9-18d4-450d-b854-daa6e83961c1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableAutoMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32150570-e401-4138-b300-6d023e7fdfe2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableAutoMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Car
        m_Car = asset.FindActionMap("Car", throwIfNotFound: true);
        m_Car_Nitro = m_Car.FindAction("Nitro", throwIfNotFound: true);
        m_Car_RotateForward = m_Car.FindAction("RotateForward", throwIfNotFound: true);
        m_Car_RotateBack = m_Car.FindAction("RotateBack", throwIfNotFound: true);
        m_Car_EnableAutoMove = m_Car.FindAction("EnableAutoMove", throwIfNotFound: true);
        m_Car_DisableAutoMove = m_Car.FindAction("DisableAutoMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Car
    private readonly InputActionMap m_Car;
    private List<ICarActions> m_CarActionsCallbackInterfaces = new List<ICarActions>();
    private readonly InputAction m_Car_Nitro;
    private readonly InputAction m_Car_RotateForward;
    private readonly InputAction m_Car_RotateBack;
    private readonly InputAction m_Car_EnableAutoMove;
    private readonly InputAction m_Car_DisableAutoMove;
    public struct CarActions
    {
        private @PlayerInputs m_Wrapper;
        public CarActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Nitro => m_Wrapper.m_Car_Nitro;
        public InputAction @RotateForward => m_Wrapper.m_Car_RotateForward;
        public InputAction @RotateBack => m_Wrapper.m_Car_RotateBack;
        public InputAction @EnableAutoMove => m_Wrapper.m_Car_EnableAutoMove;
        public InputAction @DisableAutoMove => m_Wrapper.m_Car_DisableAutoMove;
        public InputActionMap Get() { return m_Wrapper.m_Car; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CarActions set) { return set.Get(); }
        public void AddCallbacks(ICarActions instance)
        {
            if (instance == null || m_Wrapper.m_CarActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CarActionsCallbackInterfaces.Add(instance);
            @Nitro.started += instance.OnNitro;
            @Nitro.performed += instance.OnNitro;
            @Nitro.canceled += instance.OnNitro;
            @RotateForward.started += instance.OnRotateForward;
            @RotateForward.performed += instance.OnRotateForward;
            @RotateForward.canceled += instance.OnRotateForward;
            @RotateBack.started += instance.OnRotateBack;
            @RotateBack.performed += instance.OnRotateBack;
            @RotateBack.canceled += instance.OnRotateBack;
            @EnableAutoMove.started += instance.OnEnableAutoMove;
            @EnableAutoMove.performed += instance.OnEnableAutoMove;
            @EnableAutoMove.canceled += instance.OnEnableAutoMove;
            @DisableAutoMove.started += instance.OnDisableAutoMove;
            @DisableAutoMove.performed += instance.OnDisableAutoMove;
            @DisableAutoMove.canceled += instance.OnDisableAutoMove;
        }

        private void UnregisterCallbacks(ICarActions instance)
        {
            @Nitro.started -= instance.OnNitro;
            @Nitro.performed -= instance.OnNitro;
            @Nitro.canceled -= instance.OnNitro;
            @RotateForward.started -= instance.OnRotateForward;
            @RotateForward.performed -= instance.OnRotateForward;
            @RotateForward.canceled -= instance.OnRotateForward;
            @RotateBack.started -= instance.OnRotateBack;
            @RotateBack.performed -= instance.OnRotateBack;
            @RotateBack.canceled -= instance.OnRotateBack;
            @EnableAutoMove.started -= instance.OnEnableAutoMove;
            @EnableAutoMove.performed -= instance.OnEnableAutoMove;
            @EnableAutoMove.canceled -= instance.OnEnableAutoMove;
            @DisableAutoMove.started -= instance.OnDisableAutoMove;
            @DisableAutoMove.performed -= instance.OnDisableAutoMove;
            @DisableAutoMove.canceled -= instance.OnDisableAutoMove;
        }

        public void RemoveCallbacks(ICarActions instance)
        {
            if (m_Wrapper.m_CarActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICarActions instance)
        {
            foreach (var item in m_Wrapper.m_CarActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CarActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CarActions @Car => new CarActions(this);
    public interface ICarActions
    {
        void OnNitro(InputAction.CallbackContext context);
        void OnRotateForward(InputAction.CallbackContext context);
        void OnRotateBack(InputAction.CallbackContext context);
        void OnEnableAutoMove(InputAction.CallbackContext context);
        void OnDisableAutoMove(InputAction.CallbackContext context);
    }
}
