//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Car/CarActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CarActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CarActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CarActions"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""c231403f-0c6d-40e9-a9fc-d31d312d7ac3"",
            ""actions"": [
                {
                    ""name"": ""Nitro"",
                    ""type"": ""Button"",
                    ""id"": ""78da97da-5aac-4d06-a8d4-cdf29ed784bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateForward"",
                    ""type"": ""Button"",
                    ""id"": ""372ad4bc-1c03-454d-a90e-c534ebd7b200"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateBack"",
                    ""type"": ""Button"",
                    ""id"": ""78eb68be-8f11-4e04-b6e6-5a73ae1fde1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ba1e3600-4509-466e-9f91-b481c521d3a2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nitro"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57213c77-4317-48c4-84cc-51391ab17927"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ec857d9-56b0-46b2-861c-ff1921a01833"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Nitro = m_Main.FindAction("Nitro", throwIfNotFound: true);
        m_Main_RotateForward = m_Main.FindAction("RotateForward", throwIfNotFound: true);
        m_Main_RotateBack = m_Main.FindAction("RotateBack", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_Nitro;
    private readonly InputAction m_Main_RotateForward;
    private readonly InputAction m_Main_RotateBack;
    public struct MainActions
    {
        private @CarActions m_Wrapper;
        public MainActions(@CarActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Nitro => m_Wrapper.m_Main_Nitro;
        public InputAction @RotateForward => m_Wrapper.m_Main_RotateForward;
        public InputAction @RotateBack => m_Wrapper.m_Main_RotateBack;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @Nitro.started += instance.OnNitro;
            @Nitro.performed += instance.OnNitro;
            @Nitro.canceled += instance.OnNitro;
            @RotateForward.started += instance.OnRotateForward;
            @RotateForward.performed += instance.OnRotateForward;
            @RotateForward.canceled += instance.OnRotateForward;
            @RotateBack.started += instance.OnRotateBack;
            @RotateBack.performed += instance.OnRotateBack;
            @RotateBack.canceled += instance.OnRotateBack;
        }

        private void UnregisterCallbacks(IMainActions instance)
        {
            @Nitro.started -= instance.OnNitro;
            @Nitro.performed -= instance.OnNitro;
            @Nitro.canceled -= instance.OnNitro;
            @RotateForward.started -= instance.OnRotateForward;
            @RotateForward.performed -= instance.OnRotateForward;
            @RotateForward.canceled -= instance.OnRotateForward;
            @RotateBack.started -= instance.OnRotateBack;
            @RotateBack.performed -= instance.OnRotateBack;
            @RotateBack.canceled -= instance.OnRotateBack;
        }

        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActions @Main => new MainActions(this);
    public interface IMainActions
    {
        void OnNitro(InputAction.CallbackContext context);
        void OnRotateForward(InputAction.CallbackContext context);
        void OnRotateBack(InputAction.CallbackContext context);
    }
}
